server:
  port: 8082
shiro:
  ws:
    server:
      enable: true
      url: "/ws/yiyi"
  plugin-list:
    - com.bot.yiyi.plugin.RegisterPlugin
    - com.bot.yiyi.plugin.ServerPlugin
    - com.bot.yiyi.plugin.MenuPlugin
    - com.bot.yiyi.plugin.CrazyPlugin
    - com.bot.yiyi.plugin.MoneyPlugin
    - com.bot.yiyi.plugin.WifePlugin
    - com.bot.yiyi.plugin.AiPlugin
spring:
  datasource:
    url: jdbc:mysql://wuyao.love:3306/bot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wanan9644
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: wuyao.love
      port: 6379
      password: Wanan9644
      database: 0
  ai:
    openai:
#      api-key: sk-fe29bd4c8b1e41089b946317184954ea
#      base-url: https://api.deepseek.com
      api-key: sk-jyeqqjjeeavcifoigfijvdgwydyvbtvzuemtjwnntxwlrfsa
      base-url: https://api.siliconflow.cn/
      chat:
        options:
#          model: deepseek-reasoner
          model: deepseek-ai/DeepSeek-R1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bot.yiyi.pojo
