server:
  port: 8082
shiro:
  ws:
    server:
      enable: true
      url: "/ws/yiyi"
  plugin-list:
    - com.bot.yiyi.plugin.RegisterPlugin
    - com.bot.yiyi.plugin.ServerPlugin
    - com.bot.yiyi.plugin.MenuPlugin
    - com.bot.yiyi.plugin.CrazyPlugin
    - com.bot.yiyi.plugin.ImageProcessorPlugin
    - com.bot.yiyi.plugin.MoneyPlugin
    - com.bot.yiyi.plugin.WifePlugin
    - com.bot.yiyi.plugin.AiPlugin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      database: 0
  ai:
    openai:
#      api-key: key
#      base-url: https://api.deepseek.com
      api-key: key
      base-url: https://api.siliconflow.com/
      chat:
        options:
#          model: deepseek-reasoner
          model: Pro/deepseek-ai/DeepSeek-R1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bot.yiyi.pojo
bot:
  ownerQQ: qq
